version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=false
      - PERSISTENCE=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
#  director:
#    container_name: "transcribe-director"
#    image: transcribe-director:latest
#    environment:
#      - AWS_PROFILE=localstack
#      - AWS_DEFAULT_REGION="us-east-1"
#      - AWS_REGION="us-east-1"
#      - AWS_ACCESS_KEY_ID=foo
#      - AWS_SECRET_KEY_ID=foo
#      - DOCKER_HOST=unix:///var/run/docker.sock
#  worker:
#    container_name: "transcribe-worker"
#    image: transcribe-worker:latest
