version: "3.8"

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=false
      - PERSISTENCE=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
      - SERVICES=sqs
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  director:
    container_name: "director"
    image: transcribe-director:latest
    environment:
      - AWS_PROFILE=localstack
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_KEY_ID=foo
      - SOURCE_DIR=/source
      - DEST_DIR=/dest
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - DOCKER_HOST=unix:///var/run/docker.sock
    links:
      - "localstack:localstack"
    volumes:
      - "~/.aws:/root/.aws:ro"
      #- "/Users/christrotter/Desktop/source_recordings:/source"
      - "/Users/christrotter/Dropbox/Chris/Music/voice_recordings:/source"
      - "/Users/christrotter/Desktop/processed_recordings:/dest"
  worker:
    image: transcribe-worker:latest
    #container_name: "worker" #can't have static names set when using replicas, auto-sets: repo-name_servicename_qty
    environment:
      - AWS_PROFILE=localstack
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_KEY_ID=foo
      - SOURCE_DIR=/source
      - DEST_DIR=/dest
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - DOCKER_HOST=unix:///var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1024M
      mode: replicated
      replicas: 2
    links:
      - "localstack:localstack"
    volumes:
      - "~/.aws:/root/.aws:ro"
      - "/Users/christrotter/Dropbox/Chris/Music/voice_recordings:/source"
      - "/Users/christrotter/Desktop/processed_recordings:/dest"
